print("Welcome to Mad Libs!\nEnter a random word in each category.")
print("*Help*\nNoun: Naming word\nVerb: Doing word\nAdjective: Describing word")
print("(There's lots of verbs in this one, put your thinking hat on!\n")

animal = input("Enter an animal (starting with consonant): ")
food_1 = input("Enter a food: ")
noun_1 = input("Enter a noun: ")
verb_1 = input("Enter a verb: ")
verb_2 = input("Enter a verb: ")
verb_3 = input("Enter a verb: ")
verb_4 = input("Enter a verb: ")
noun_2 = input("Enter a noun: ")
location_1 = input("Enter a location: ")
noun_3 = input("Enter a noun: ")
noun_4 = input("Enter a noun: ")
location_2 = input("Enter a location: ")
verb_5 = input("Enter a verb: ")
food_2 = input("Enter a food: ")
game = input("Enter a game: ")
verb_6 = input("Enter a verb: ")
noun_5 = input("Enter a noun: ")
noun_6 = input("Enter a noun: ")
noun_7 = input("Enter a plural noun: ")
verb_7 = input("Enter a verb ending with 'ing': ")
verb_8 = input("Enter a verb: ")
noun_8 = input("Enter a plural noun: ")
verb_9 = input("Enter a verb: ")

print("Here is your Mad Lib!\n")
print("If you give a " + animal + " a " + food_1 + ", they are going to ask for a " + noun_1 + ".")
print("When you give them the " + noun_1 + ", they will want to " + verb_1 + ".")
print("When they are finished, they will " + verb_2 + ".")
print("Then they will " + verb_3 + " and " + verb_4 + " into a " + noun_2 + ".")
print("Since that doesn't work out, they will want to go to " + location_1 + ".")
print("On the way, they will see a " + noun_3 + " and want a " + noun_4 + ".")
print("Then you will have to take them to the " + location_2 + ". They will " + verb_5 + ".")
print("When they are done, they will ask you for some " + food_2 + ".")
print("On the way home they will start a game of " + game + ".")
print("When you finally get home, you'll have to " + verb_6 + ".")
print("Then they'll want a " + noun_5 + ".")
print("You'll have to find a " + noun_6 + " and some " + noun_7 + ".")
print("When they see the " + noun_7 + ", they will start " + verb_7 + ".")
print("Then they will " + verb_8 + " out of a " + noun_8 + ".")
print("Of course, when they are finished they will want to " + verb_9 + ".")
print("So, they will ask for a " + noun_1 + ".")
print("And the chances are, if you give them a " + noun_1 + ", they are going to want a " + food_1 + ".\n")
print("The End!")